_: {
  imports = [
    ./alpha.nix
    ./autopairs.nix
    ./blink.nix
    ./bufferline.nix
    ./colorscheme.nix
    ./comment.nix
    ./conform.nix
    ./fidget.nix
    ./gitblame.nix
    ./gitsigns.nix
    ./hop.nix
    ./lint.nix
    ./lsp.nix
    ./lspsaga.nix
    ./lualine.nix
    ./lzn.nix
    ./markview.nix
    ./mini
    ./nonels.nix
    ./smartsplits.nix
    ./snacks
    ./spectre.nix
    ./telescope.nix
    ./treesittertextobjects.nix
    ./treesitter.nix
    ./trouble.nix
    ./trunk.nix
    ./undotree.nix
    ./webdevicons.nix
    ./whichkey.nix
  ];
}
